import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'fs'
import { tmpdir } from 'os'
import { join } from 'path'

import { z } from 'zod'

/** Env var the generated reporter reads to find where to write the dump. */
export const DOCKER_CONFIG_DUMP_ENV = 'CRVY_RPRTR_CONFIG_DUMP'

/**
 * Runtime-generated `v2` reporter (fontconfig precedent): written as a `.cjs` file
 * so no dist entry, knip entry, or exports-map change is needed. Playwright loads
 * it as the second reporter of the preflight listing and hands it the resolved
 * config on `onConfigure` — array-form `webServer` and `use.baseURL` are only
 * reachable there.
 *
 * The reporter must declare `version() { return 'v2' }`: legacy reporters receive
 * the config in `onBegin`, after the listing has already collected tests.
 * Every extraction step is guarded, because a reporter that throws breaks the
 * listing the pin preflight depends on.
 */
export const CONFIG_DUMP_REPORTER_SOURCE = `// Generated by crvy-rprtr. Writes the resolved Playwright config summary.
const fs = require('fs')

const WEB_SERVER_KEYS = ['command', 'url', 'port', 'name', 'reuseExistingServer']

function pickWebServer(entry) {
  const out = {}
  if (entry === null || typeof entry !== 'object') return out
  for (const key of WEB_SERVER_KEYS) {
    const value = entry[key]
    if (value !== undefined) out[key] = value
  }
  return out
}

function internalConfig(config) {
  if (config === null || typeof config !== 'object') return null
  for (const symbol of Object.getOwnPropertySymbols(config)) {
    if (symbol.description !== 'configInternalSymbol') continue
    const internal = config[symbol]
    if (internal !== null && typeof internal === 'object') return internal
  }
  return null
}

function collectWebServers(config) {
  const internal = internalConfig(config)
  const listed = internal === null ? undefined : internal.webServers
  if (Array.isArray(listed)) return listed.map(pickWebServer)
  const single = config === null || typeof config !== 'object' ? undefined : config.webServer
  if (single === null || typeof single !== 'object' || Array.isArray(single)) return []
  return [pickWebServer(single)]
}

function collectProjects(config) {
  const projects = config === null || typeof config !== 'object' ? undefined : config.projects
  if (!Array.isArray(projects)) return []
  const out = []
  for (const project of projects) {
    if (project === null || typeof project !== 'object') continue
    const entry = {}
    if (typeof project.name === 'string') entry.name = project.name
    const use = project.use
    if (use !== null && typeof use === 'object' && typeof use.baseURL === 'string') entry.baseURL = use.baseURL
    if (Object.keys(entry).length > 0) out.push(entry)
  }
  return out
}

class ConfigDumpReporter {
  version() {
    return 'v2'
  }

  onConfigure(config) {
    const target = process.env.${DOCKER_CONFIG_DUMP_ENV}
    if (target === undefined || target === '') return
    try {
      const dump = { webServers: collectWebServers(config), projects: collectProjects(config) }
      fs.writeFileSync(target, JSON.stringify(dump), 'utf8')
    } catch {
      // Diagnostics must never break the listing.
    }
  }
}

module.exports = ConfigDumpReporter
`

export const DockerWebServerSchema = z.object({
  command: z.string().optional(),
  url: z.string().optional(),
  port: z.number().optional(),
  name: z.string().optional(),
  reuseExistingServer: z.boolean().optional(),
})

export type DockerWebServer = z.infer<typeof DockerWebServerSchema>

export const DockerConfigProjectSchema = z.object({
  name: z.string().optional(),
  baseURL: z.string().optional(),
})

export const DockerConfigSummarySchema = z.object({
  webServers: z.array(DockerWebServerSchema),
  projects: z.array(DockerConfigProjectSchema),
})

export type DockerConfigSummary = z.infer<typeof DockerConfigSummarySchema>

/** Stable temp path so repeated runs reuse one reporter file instead of littering the temp dir. */
export function configDumpReporterPath(): string {
  return join(tmpdir(), 'crvy-rprtr', 'config-dump-reporter.cjs')
}

/** Pid-scoped dump path: concurrent servers must not read each other's dumps. */
export function configDumpPath(pid: number = process.pid): string {
  return join(tmpdir(), 'crvy-rprtr', `config-dump-${pid}.json`)
}

/** Writes the generated reporter and returns its path. Synchronous: the path goes into the spawn below. */
export function ensureConfigDumpReporter(): string {
  const path = configDumpReporterPath()
  mkdirSync(join(tmpdir(), 'crvy-rprtr'), { recursive: true })
  writeFileSync(path, CONFIG_DUMP_REPORTER_SOURCE, 'utf8')
  return path
}

/**
 * Reads the dump the generated reporter wrote and deletes it. Null when the file
 * is missing, unreadable, or does not parse into the expected shape — callers
 * treat that as "summary unknown", never as an error.
 */
export function readAndDeleteConfigDump(path: string): DockerConfigSummary | null {
  try {
    const parsed: unknown = JSON.parse(readFileSync(path, 'utf8'))
    const result = DockerConfigSummarySchema.safeParse(parsed)
    return result.success ? result.data : null
  } catch {
    return null
  } finally {
    rmSync(path, { force: true })
  }
}
