import { chromium, expect, test } from '@playwright/test'

import { rootFontconfigPath } from '../../src/fontconfig'
import { DETERMINISTIC_CHROMIUM_ARGS, applyGrayscaleFontRendering } from '../../src/rendering'

/** Text-heavy enough that subpixel fringes would move thousands of bytes. */
const PAGE = `<!doctype html><meta charset="utf-8"><body style="margin:0;background:#fff">
<p style="font:16px/1.4 sans-serif;width:320px">The quick brown fox jumps over the lazy dog, 0123456789,
and then keeps going so the paragraph wraps across several lines of antialiased text.</p>
</body>`

async function capture(launchOptions: Parameters<typeof chromium.launch>[0]): Promise<Buffer> {
  const browser = await chromium.launch(launchOptions)
  try {
    const page = await browser.newPage({ viewport: { width: 360, height: 160 } })
    await page.setContent(PAGE)
    return await page.screenshot()
  } finally {
    await browser.close()
  }
}

/**
 * crvy-rprtr pins grayscale antialiasing two different ways — a fontconfig the
 * browser reads from its environment (the reporter, both run modes, and
 * `deterministicLaunchOptions`) and a Chromium switch (`--disable-lcd-text`).
 * Baselines are generated by one and verified by another, so the two have to
 * agree pixel for pixel. That equivalence was verified by hand and recorded in
 * a comment; this asserts it.
 *
 * Linux-only: elsewhere there is no subpixel antialiasing to turn off, so the
 * comparison would pass without testing anything.
 */
test.describe('font rendering equivalence', () => {
  test.skip(process.platform !== 'linux', 'fontconfig drives text rendering on Linux only')

  test('the fontconfig pin and --disable-lcd-text render identically', async () => {
    // The crvy reporter pins this very process in its constructor, so by the time
    // a test runs the environment is normally already pinned. Both outcomes mean
    // the same thing here — the config is in place — and anything else means the
    // comparison would not be testing the pin at all.
    const env: Record<string, string | undefined> = { ...process.env }
    const pin = applyGrayscaleFontRendering(env)
    const pinnedPath = pin.pinned ? pin.path : rootFontconfigPath()
    if (!pin.pinned) {
      expect(pin.reason, 'the run must be pinned for this comparison to mean anything').toBe('already-pinned')
    }
    expect(env.FONTCONFIG_FILE).toBe(pinnedPath)

    const pinnedEnv: Record<string, string> = {}
    for (const [key, value] of Object.entries(env)) {
      if (value !== undefined) pinnedEnv[key] = value
    }

    const viaFontconfig = await capture({ env: pinnedEnv })
    const viaSwitch = await capture({ args: [...DETERMINISTIC_CHROMIUM_ARGS] })

    expect(viaFontconfig.equals(viaSwitch)).toBe(true)
  })
})
